"""
Job matching algorithm implementation.
Author: Generated by Agentic AI for CS5542 Challenge 1
"""

from typing import List, Tuple, Dict
import math
from src.models import Seeker, Opportunity, MatchResult, ExperienceLevel, WorkMode, WorkType
from src.utils import (
    calculate_skill_match, 
    calculate_experience_match,
    calculate_salary_match,
    get_missing_skills,
    keyword_match_percentage
)


class JobMatcher:
    """
    Implements the weighted job matching algorithm.
    
    Matching weights:
    - Skills: 30%
    - Experience: 25%
    - Location: 15%
    - Salary: 15%
    - Work Mode: 5%
    - Work Type: 5%
    - Career Goals: 5%
    """
    
    # Weights for each matching criterion (must sum to 1.0)
    WEIGHTS = {
        "skills": 0.30,
        "experience": 0.25,
        "location": 0.15,
        "salary": 0.15,
        "work_mode": 0.05,
        "work_type": 0.05,
        "career_goals": 0.05
    }
    
    def calculate_match(self, seeker: Seeker, opportunity: Opportunity) -> MatchResult:
        """
        Calculate the match percentage between a seeker and an opportunity.
        
        Args:
            seeker: Job seeker profile
            opportunity: Job opportunity profile
            
        Returns:
            MatchResult object with detailed match information
        """
        
        # Calculate individual match percentages
        skill_match = self._calculate_skill_match(seeker, opportunity)
        experience_match = self._calculate_experience_match(seeker, opportunity)
        location_match = self._calculate_location_match(seeker, opportunity)
        salary_match = self._calculate_salary_match(seeker, opportunity)
        work_mode_match = self._calculate_work_mode_match(seeker, opportunity)
        work_type_match = self._calculate_work_type_match(seeker, opportunity)
        career_goals_match = self._calculate_career_goals_match(seeker, opportunity)
        
        # Calculate weighted overall score
        overall_match = (
            skill_match * self.WEIGHTS["skills"] +
            experience_match * self.WEIGHTS["experience"] +
            location_match * self.WEIGHTS["location"] +
            salary_match * self.WEIGHTS["salary"] +
            work_mode_match * self.WEIGHTS["work_mode"] +
            work_type_match * self.WEIGHTS["work_type"] +
            career_goals_match * self.WEIGHTS["career_goals"]
        )
        
        # Get skill details
        matched_skills = self._get_matched_skills(seeker, opportunity)
        missing_skills = self._get_missing_skills(seeker, opportunity)
        matched_preferred_skills = self._get_matched_preferred_skills(seeker, opportunity)
        
        # Generate explanation and recommendation
        explanation = self._generate_explanation(
            seeker, opportunity, overall_match, 
            skill_match, experience_match, location_match,
            matched_skills, missing_skills
        )
        
        recommendation = self._generate_recommendation(
            overall_match, missing_skills, career_goals_match
        )
        
        # Create and return result
        return MatchResult(
            seeker_name=seeker.name,
            job_id=opportunity.job_id,
            job_title=opportunity.title,
            company=opportunity.company,
            overall_match_percentage=round(overall_match, 2),
            skill_match_percentage=round(skill_match, 2),
            experience_match_percentage=round(experience_match, 2),
            location_match_percentage=round(location_match, 2),
            salary_match_percentage=round(salary_match, 2),
            work_mode_match_percentage=round(work_mode_match, 2),
            work_type_match_percentage=round(work_type_match, 2),
            career_goals_match_percentage=round(career_goals_match, 2),
            matched_skills=matched_skills,
            missing_skills=missing_skills,
            matched_preferred_skills=matched_preferred_skills,
            explanation=explanation,
            recommendation=recommendation
        )
    
    def _calculate_skill_match(self, seeker: Seeker, opportunity: Opportunity) -> float:
        """Calculate skill match percentage (0-100)."""
        if not opportunity.required_skills:
            return 100.0
        
        matched_count = 0
        for req_skill in opportunity.required_skills:
            for seeker_skill in seeker.skills:
                if self._skill_matches(seeker_skill, req_skill):
                    matched_count += 1
                    break
        
        required_match_score = (matched_count / len(opportunity.required_skills)) * 100 if opportunity.required_skills else 0
        
        # Bonus for preferred skills
        preferred_bonus = 0.0
        if opportunity.preferred_skills:
            preferred_matched = 0
            for pref_skill in opportunity.preferred_skills:
                for seeker_skill in seeker.skills:
                    if self._skill_matches(seeker_skill, pref_skill):
                        preferred_matched += 1
                        break
            preferred_bonus = (preferred_matched / len(opportunity.preferred_skills)) * 10  # Max 10 point bonus
        
        return min(100.0, required_match_score + preferred_bonus)
    
    def _calculate_experience_match(self, seeker: Seeker, opportunity: Opportunity) -> float:
        """Calculate experience level match percentage (0-100)."""
        seeker_level_value = self._experience_level_to_value(seeker.experience_level)
        required_level_value = self._experience_level_to_value(opportunity.experience_level_required)
        
        if seeker_level_value >= required_level_value:
            return 100.0
        
        # Partial credit for being close to required level
        match_percentage = (seeker_level_value / required_level_value) * 100
        return min(100.0, match_percentage)
    
    def _calculate_location_match(self, seeker: Seeker, opportunity: Opportunity) -> float:
        """Calculate location match percentage (0-100)."""
        # Check if seeker is located in opportunity's locations
        if not opportunity.locations:
            return 100.0
        
        for opp_location in opportunity.locations:
            for seeker_location in seeker.preferred_locations:
                if self._location_matches(seeker_location, opp_location):
                    return 100.0
        
        # Check if relocation is acceptable
        if seeker.willing_to_relocate and opportunity.allows_relocation:
            return 80.0  # Partial match if relocation is possible
        
        # No match if locations incompatible
        return 0.0
    
    def _calculate_salary_match(self, seeker: Seeker, opportunity: Opportunity) -> float:
        """Calculate salary range match percentage (0-100)."""
        # If no salary expectations from seeker, assume 100% match
        if seeker.salary_expectation_min is None and seeker.salary_expectation_max is None:
            return 100.0
        
        # If no salary info from opportunity, assume 100% match
        if opportunity.salary_min is None and opportunity.salary_max is None:
            return 100.0
        
        # Check for overlap in salary ranges
        seeker_min = seeker.salary_expectation_min or 0
        seeker_max = seeker.salary_expectation_max or float('inf')
        opp_min = opportunity.salary_min or 0
        opp_max = opportunity.salary_max or float('inf')
        
        # Check if ranges overlap
        if opp_max < seeker_min or seeker_max < opp_min:
            return 0.0  # No overlap
        
        # Calculate overlap percentage
        overlap_start = max(seeker_min, opp_min)
        overlap_end = min(seeker_max, opp_max)
        overlap = max(0, overlap_end - overlap_start)
        
        seeker_range = seeker_max - seeker_min
        if seeker_range == 0:
            return 100.0
        
        return min(100.0, (overlap / seeker_range) * 100)
    
    def _calculate_work_mode_match(self, seeker: Seeker, opportunity: Opportunity) -> float:
        """Calculate work mode match (remote/hybrid/onsite) - 0 or 100."""
        if not seeker.work_mode_preference:
            return 100.0
        
        if opportunity.work_mode in seeker.work_mode_preference:
            return 100.0
        
        return 0.0
    
    def _calculate_work_type_match(self, seeker: Seeker, opportunity: Opportunity) -> float:
        """Calculate work type match (full/part/contract/intern) - 0 or 100."""
        if not seeker.work_type_preference:
            return 100.0
        
        if opportunity.work_type in seeker.work_type_preference:
            return 100.0
        
        return 0.0
    
    def _calculate_career_goals_match(self, seeker: Seeker, opportunity: Opportunity) -> float:
        """Calculate career goals alignment match percentage (0-100)."""
        if not seeker.career_goals:
            return 100.0
        
        # Combine job title, responsibilities, and company info for goal matching
        job_info = f"{opportunity.title} {opportunity.description} {' '.join(opportunity.responsibilities)}"
        
        matched_goals = 0
        for goal in seeker.career_goals:
            if keyword_match_percentage(goal.lower(), job_info.lower()) > 30:
                matched_goals += 1
        
        return (matched_goals / len(seeker.career_goals)) * 100 if seeker.career_goals else 100.0
    
    def _get_matched_skills(self, seeker: Seeker, opportunity: Opportunity) -> List[str]:
        """Get list of required skills matched by seeker."""
        matched = []
        for req_skill in opportunity.required_skills:
            for seeker_skill in seeker.skills:
                if self._skill_matches(seeker_skill, req_skill):
                    matched.append(req_skill)
                    break
        return matched
    
    def _get_missing_skills(self, seeker: Seeker, opportunity: Opportunity) -> List[str]:
        """Get list of required skills missing from seeker."""
        missing = []
        for req_skill in opportunity.required_skills:
            found = False
            for seeker_skill in seeker.skills:
                if self._skill_matches(seeker_skill, req_skill):
                    found = True
                    break
            if not found:
                missing.append(req_skill)
        return missing
    
    def _get_matched_preferred_skills(self, seeker: Seeker, opportunity: Opportunity) -> List[str]:
        """Get list of preferred skills matched by seeker."""
        matched = []
        for pref_skill in opportunity.preferred_skills:
            for seeker_skill in seeker.skills:
                if self._skill_matches(seeker_skill, pref_skill):
                    matched.append(pref_skill)
                    break
        return matched
    
    @staticmethod
    def _skill_matches(seeker_skill: str, required_skill: str) -> bool:
        """Check if seeker skill matches required skill (case-insensitive)."""
        seeker_skill_lower = seeker_skill.lower()
        required_skill_lower = required_skill.lower()
        
        # Exact match
        if seeker_skill_lower == required_skill_lower:
            return True
        
        # Common abbreviations and variations
        variations = {
            "javascript": ["js", "node.js", "nodejs"],
            "python": ["py"],
            "java": ["jvm"],
            "c++": ["cpp", "c plus plus"],
            "c#": ["csharp", "c sharp"],
            "machine learning": ["ml", "deep learning"],
            "artificial intelligence": ["ai"],
            "aws": ["amazon web services"],
            "gcp": ["google cloud platform"],
            "sql": ["mysql", "postgresql", "mariadb"],
            "react": ["reactjs"],
            "angular": ["angularjs"],
            "vue": ["vuejs"],
        }
        
        # Check variations
        for key, values in variations.items():
            if seeker_skill_lower == key and required_skill_lower in values:
                return True
            if seeker_skill_lower in values and required_skill_lower == key:
                return True
        
        return False
    
    @staticmethod
    def _location_matches(seeker_location: str, opportunity_location: str) -> bool:
        """Check if locations match (case-insensitive)."""
        seeker_loc = seeker_location.lower().strip()
        opp_loc = opportunity_location.lower().strip()
        return seeker_loc == opp_loc
    
    @staticmethod
    def _experience_level_to_value(level: ExperienceLevel) -> int:
        """Convert experience level to numeric value."""
        levels = {
            ExperienceLevel.ENTRY: 1,
            ExperienceLevel.JUNIOR: 2,
            ExperienceLevel.SENIOR: 3,
            ExperienceLevel.LEAD: 4,
            ExperienceLevel.EXECUTIVE: 5
        }
        return levels.get(level, 1)
    
    @staticmethod
    def _generate_explanation(seeker: Seeker, opportunity: Opportunity, 
                            overall_match: float, skill_match: float, 
                            experience_match: float, location_match: float,
                            matched_skills: List[str], missing_skills: List[str]) -> str:
        """Generate human-readable explanation of match."""
        explanation = f"{seeker.name}, you have a {overall_match}% match with the {opportunity.title} position at {opportunity.company}. "
        
        if skill_match >= 80:
            explanation += f"You have strong technical skills alignment with {len(matched_skills)} of {len(opportunity.required_skills)} required skills. "
        elif skill_match >= 50:
            explanation += f"You have partial skills alignment, matching {len(matched_skills)} required skills but missing {len(missing_skills)}. "
        else:
            explanation += f"Your skills partially align with this role. You match {len(matched_skills)} required skills but need to develop {len(missing_skills)} additional skills. "
        
        if experience_match >= 80:
            explanation += f"Your experience level aligns well with this role's requirements. "
        else:
            explanation += f"Your experience level is somewhat junior compared to this role's requirements. "
        
        if location_match == 100:
            explanation += f"Location is a perfect match. "
        elif location_match > 0:
            explanation += f"Relocation may be required or considered. "
        else:
            explanation += f"Location does not match your preferences. "
        
        return explanation
    
    @staticmethod
    def _generate_recommendation(overall_match: float, missing_skills: List[str], career_goals_match: float) -> str:
        """Generate recommendation based on match."""
        if overall_match >= 85:
            return "Strong fit! We recommend applying for this role immediately."
        elif overall_match >= 70:
            return f"Good fit! Consider applying. To strengthen your candidacy, consider developing: {', '.join(missing_skills[:3]) if missing_skills else 'your experience'}."
        elif overall_match >= 50:
            return f"Moderate fit. This role could help advance your career, but you may need to develop some skills first: {', '.join(missing_skills[:3]) if missing_skills else 'technical skills'}."
        else:
            return "Not a strong match. Consider exploring roles more aligned with your current skills and experience."
    
    def rank_opportunities(self, seeker: Seeker, opportunities: List[Opportunity], 
                          min_match_threshold: float = 50.0) -> List[MatchResult]:
        """
        Rank a list of opportunities for a seeker.
        
        Args:
            seeker: Job seeker profile
            opportunities: List of job opportunities
            min_match_threshold: Minimum match percentage to include (default 50%)
            
        Returns:
            List of MatchResult objects sorted by overall match percentage (highest first)
        """
        results = []
        for opportunity in opportunities:
            match_result = self.calculate_match(seeker, opportunity)
            if match_result.overall_match_percentage >= min_match_threshold:
                results.append(match_result)
        
        # Sort by overall match percentage (highest first)
        results.sort(key=lambda x: x.overall_match_percentage, reverse=True)
        return results
