"""
Data models for job seeker and opportunity matching system.
Author: Generated by Agentic AI for CS5542 Challenge 1
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional
from enum import Enum


class ExperienceLevel(Enum):
    """Experience levels supported by the matching system."""
    ENTRY = "entry"
    JUNIOR = "junior"
    SENIOR = "senior"
    LEAD = "lead"
    EXECUTIVE = "executive"


class WorkMode(Enum):
    """Work mode preferences."""
    REMOTE = "remote"
    HYBRID = "hybrid"
    ONSITE = "onsite"


class WorkType(Enum):
    """Employment type preferences."""
    FULL_TIME = "full"
    PART_TIME = "part"
    CONTRACT = "contract"
    INTERNSHIP = "intern"


@dataclass
class Seeker:
    """Represents a job seeker with their profile information."""
    
    # Basic information
    name: str
    email: Optional[str] = None
    phone: Optional[str] = None
    
    # Career information
    career_goals: List[str] = field(default_factory=list)
    industry_interests: List[str] = field(default_factory=list)
    experience_level: ExperienceLevel = ExperienceLevel.JUNIOR
    
    # Skills and qualifications
    skills: List[str] = field(default_factory=list)
    certifications: List[str] = field(default_factory=list)
    
    # Education
    education: str = ""  # e.g., "Bachelor's in Computer Science"
    
    # Preferences
    preferred_locations: List[str] = field(default_factory=list)
    willing_to_relocate: bool = False
    work_mode_preference: List[WorkMode] = field(default_factory=list)
    work_type_preference: List[WorkType] = field(default_factory=list)
    
    # Compensation
    salary_expectation_min: Optional[float] = None
    salary_expectation_max: Optional[float] = None
    
    # Availability
    availability_days: Optional[int] = None  # Days until available
    
    def to_dict(self) -> Dict:
        """Convert seeker to dictionary representation."""
        return {
            "name": self.name,
            "email": self.email,
            "phone": self.phone,
            "career_goals": self.career_goals,
            "industry_interests": self.industry_interests,
            "experience_level": self.experience_level.value,
            "skills": self.skills,
            "certifications": self.certifications,
            "education": self.education,
            "preferred_locations": self.preferred_locations,
            "willing_to_relocate": self.willing_to_relocate,
            "work_mode_preference": [m.value for m in self.work_mode_preference],
            "work_type_preference": [t.value for t in self.work_type_preference],
            "salary_expectation": {
                "min": self.salary_expectation_min,
                "max": self.salary_expectation_max
            },
            "availability_days": self.availability_days
        }


@dataclass
class Opportunity:
    """Represents a job opportunity/listing."""
    
    # Basic information
    job_id: str
    title: str
    company: str
    description: Optional[str] = None
    
    # Responsibilities
    responsibilities: List[str] = field(default_factory=list)
    
    # Requirements
    required_skills: List[str] = field(default_factory=list)
    preferred_skills: List[str] = field(default_factory=list)
    experience_level_required: ExperienceLevel = ExperienceLevel.JUNIOR
    experience_years_required: int = 0
    
    # Education and certifications
    education_required: Optional[str] = None
    certifications_required: List[str] = field(default_factory=list)
    
    # Location and work details
    locations: List[str] = field(default_factory=list)
    allows_relocation: bool = False
    work_mode: WorkMode = WorkMode.ONSITE
    work_type: WorkType = WorkType.FULL_TIME
    
    # Compensation
    salary_min: Optional[float] = None
    salary_max: Optional[float] = None
    benefits: List[str] = field(default_factory=list)
    
    # Additional info
    posted_date: Optional[str] = None
    application_deadline: Optional[str] = None
    
    def to_dict(self) -> Dict:
        """Convert opportunity to dictionary representation."""
        return {
            "job_id": self.job_id,
            "title": self.title,
            "company": self.company,
            "description": self.description,
            "responsibilities": self.responsibilities,
            "required_skills": self.required_skills,
            "preferred_skills": self.preferred_skills,
            "experience_level_required": self.experience_level_required.value,
            "experience_years_required": self.experience_years_required,
            "education_required": self.education_required,
            "certifications_required": self.certifications_required,
            "locations": self.locations,
            "allows_relocation": self.allows_relocation,
            "work_mode": self.work_mode.value,
            "work_type": self.work_type.value,
            "salary": {
                "min": self.salary_min,
                "max": self.salary_max
            },
            "benefits": self.benefits,
            "posted_date": self.posted_date,
            "application_deadline": self.application_deadline
        }


@dataclass
class MatchResult:
    """Result of matching a seeker to an opportunity."""
    
    seeker_name: str
    job_id: str
    job_title: str
    company: str
    
    # Match scores (0-100)
    overall_match_percentage: float
    skill_match_percentage: float
    experience_match_percentage: float
    location_match_percentage: float
    salary_match_percentage: float
    work_mode_match_percentage: float
    work_type_match_percentage: float
    career_goals_match_percentage: float
    
    # Details
    matched_skills: List[str] = field(default_factory=list)
    missing_skills: List[str] = field(default_factory=list)
    matched_preferred_skills: List[str] = field(default_factory=list)
    
    # Feedback
    explanation: str = ""
    recommendation: str = ""
    
    def to_dict(self) -> Dict:
        """Convert match result to dictionary representation."""
        return {
            "seeker": self.seeker_name,
            "job": {
                "id": self.job_id,
                "title": self.job_title,
                "company": self.company
            },
            "match_scores": {
                "overall": self.overall_match_percentage,
                "skills": self.skill_match_percentage,
                "experience": self.experience_match_percentage,
                "location": self.location_match_percentage,
                "salary": self.salary_match_percentage,
                "work_mode": self.work_mode_match_percentage,
                "work_type": self.work_type_match_percentage,
                "career_goals": self.career_goals_match_percentage
            },
            "skills": {
                "matched": self.matched_skills,
                "missing": self.missing_skills,
                "matched_preferred": self.matched_preferred_skills
            },
            "feedback": {
                "explanation": self.explanation,
                "recommendation": self.recommendation
            }
        }
