"""
Utility functions for job matching system.
Author: Generated by Agentic AI for CS5542 Challenge 1
"""

from typing import List, Dict, Tuple
import json


def calculate_skill_match(seeker_skills: List[str], required_skills: List[str], 
                        preferred_skills: List[str] = None) -> Tuple[float, List[str], List[str]]:
    """
    Calculate skill match percentage between seeker skills and required skills.
    
    Args:
        seeker_skills: List of skills the seeker has
        required_skills: List of required skills for the job
        preferred_skills: List of preferred skills (optional)
        
    Returns:
        Tuple of (match_percentage, matched_skills, missing_skills)
    """
    if not required_skills:
        return 100.0, seeker_skills, []
    
    matched = []
    missing = []
    
    for req_skill in required_skills:
        found = False
        for seeker_skill in seeker_skills:
            if skill_matches(seeker_skill, req_skill):
                matched.append(req_skill)
                found = True
                break
        
        if not found:
            missing.append(req_skill)
    
    match_percentage = (len(matched) / len(required_skills)) * 100
    
    # Add bonus for preferred skills
    if preferred_skills:
        preferred_matched = sum(1 for pref in preferred_skills 
                               if any(skill_matches(seeker_skill, pref) 
                                     for seeker_skill in seeker_skills))
        bonus = (preferred_matched / len(preferred_skills)) * 10  # Max 10 point bonus
        match_percentage = min(100.0, match_percentage + bonus)
    
    return match_percentage, matched, missing


def calculate_experience_match(seeker_level: str, required_level: str, 
                              seeker_years: int = 0, required_years: int = 0) -> float:
    """
    Calculate experience level match percentage.
    
    Args:
        seeker_level: Seeker's experience level (entry/junior/senior/lead/executive)
        required_level: Required experience level for the job
        seeker_years: Number of years of experience (optional)
        required_years: Required years of experience (optional)
        
    Returns:
        Match percentage (0-100)
    """
    level_hierarchy = {
        "entry": 1,
        "junior": 2,
        "senior": 3,
        "lead": 4,
        "executive": 5
    }
    
    seeker_value = level_hierarchy.get(seeker_level.lower(), 1)
    required_value = level_hierarchy.get(required_level.lower(), 1)
    
    # Check level match
    if seeker_value >= required_value:
        level_match = 100.0
    else:
        level_match = (seeker_value / required_value) * 100
    
    # Check years of experience
    if required_years > 0 and seeker_years > 0:
        if seeker_years >= required_years:
            years_match = 100.0
        else:
            years_match = (seeker_years / required_years) * 100
        
        # Average the two scores
        return (level_match + years_match) / 2
    
    return level_match


def calculate_salary_match(seeker_min: float, seeker_max: float, 
                          job_min: float, job_max: float) -> float:
    """
    Calculate salary range match percentage.
    
    Args:
        seeker_min: Seeker's minimum salary expectation
        seeker_max: Seeker's maximum salary expectation
        job_min: Job's minimum salary
        job_max: Job's maximum salary
        
    Returns:
        Match percentage (0-100)
    """
    if seeker_min is None or seeker_max is None or job_min is None or job_max is None:
        return 100.0
    
    # Check for overlap
    if job_max < seeker_min or seeker_max < job_min:
        return 0.0  # No overlap
    
    # Calculate overlap
    overlap_start = max(seeker_min, job_min)
    overlap_end = min(seeker_max, job_max)
    overlap = overlap_end - overlap_start
    
    seeker_range = seeker_max - seeker_min
    if seeker_range == 0:
        return 100.0
    
    return min(100.0, (overlap / seeker_range) * 100)


def skill_matches(seeker_skill: str, required_skill: str) -> bool:
    """
    Check if seeker skill matches required skill.
    Handles common abbreviations and variations.
    
    Args:
        seeker_skill: Skill from seeker's profile
        required_skill: Required skill from job posting
        
    Returns:
        True if skills match, False otherwise
    """
    seeker_skill_lower = seeker_skill.lower().strip()
    required_skill_lower = required_skill.lower().strip()
    
    # Exact match
    if seeker_skill_lower == required_skill_lower:
        return True
    
    # Common abbreviations and variations
    variations = {
        "javascript": ["js", "node.js", "nodejs"],
        "python": ["py"],
        "java": ["jvm"],
        "c++": ["cpp", "c plus plus"],
        "c#": ["csharp", "c sharp"],
        "machine learning": ["ml", "deep learning"],
        "artificial intelligence": ["ai"],
        "aws": ["amazon web services"],
        "gcp": ["google cloud platform"],
        "sql": ["mysql", "postgresql", "mariadb"],
        "react": ["reactjs"],
        "angular": ["angularjs"],
        "vue": ["vuejs"],
        "docker": ["containerization"],
        "kubernetes": ["k8s"],
    }
    
    # Check variations
    for key, values in variations.items():
        if seeker_skill_lower == key and required_skill_lower in values:
            return True
        if seeker_skill_lower in values and required_skill_lower == key:
            return True
    
    return False


def get_missing_skills(seeker_skills: List[str], required_skills: List[str]) -> List[str]:
    """Get list of required skills missing from seeker."""
    missing = []
    for req_skill in required_skills:
        if not any(skill_matches(seeker_skill, req_skill) for seeker_skill in seeker_skills):
            missing.append(req_skill)
    return missing


def keyword_match_percentage(text1: str, text2: str, min_word_length: int = 3) -> float:
    """
    Calculate keyword match percentage between two text strings.
    
    Args:
        text1: First text
        text2: Second text
        min_word_length: Minimum word length to consider
        
    Returns:
        Match percentage (0-100)
    """
    # Split text into keywords
    words1 = set(w for w in text1.split() if len(w) >= min_word_length)
    words2 = set(w for w in text2.split() if len(w) >= min_word_length)
    
    if not words1 or not words2:
        return 0.0
    
    # Calculate overlap
    overlap = len(words1.intersection(words2))
    total = len(words1.union(words2))
    
    if total == 0:
        return 0.0
    
    return (overlap / total) * 100


def load_seekers_from_json(filepath: str) -> List[Dict]:
    """Load seeker profiles from JSON file."""
    with open(filepath, 'r') as f:
        return json.load(f)


def load_opportunities_from_json(filepath: str) -> List[Dict]:
    """Load job opportunities from JSON file."""
    with open(filepath, 'r') as f:
        return json.load(f)


def save_match_results_to_json(results: List[Dict], filepath: str) -> None:
    """Save match results to JSON file."""
    with open(filepath, 'w') as f:
        json.dump(results, f, indent=2)


def format_match_report(match_result) -> str:
    """Format a match result as a human-readable report."""
    report = f"""
{'='*70}
JOB MATCH REPORT
{'='*70}

Seeker: {match_result.seeker_name}
Position: {match_result.job_title} at {match_result.company}
Job ID: {match_result.job_id}

OVERALL MATCH: {match_result.overall_match_percentage}%

MATCH BREAKDOWN:
  - Skills Match:        {match_result.skill_match_percentage}%
  - Experience Match:    {match_result.experience_match_percentage}%
  - Location Match:      {match_result.location_match_percentage}%
  - Salary Match:        {match_result.salary_match_percentage}%
  - Work Mode Match:     {match_result.work_mode_match_percentage}%
  - Work Type Match:     {match_result.work_type_match_percentage}%
  - Career Goals Match:  {match_result.career_goals_match_percentage}%

SKILLS ANALYSIS:
  Matched Skills ({len(match_result.matched_skills)}):
    {', '.join(match_result.matched_skills) if match_result.matched_skills else 'None'}
  
  Missing Skills ({len(match_result.missing_skills)}):
    {', '.join(match_result.missing_skills) if match_result.missing_skills else 'None'}
  
  Matched Preferred Skills ({len(match_result.matched_preferred_skills)}):
    {', '.join(match_result.matched_preferred_skills) if match_result.matched_preferred_skills else 'None'}

EXPLANATION:
  {match_result.explanation}

RECOMMENDATION:
  {match_result.recommendation}

{'='*70}
"""
    return report
